# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f93e2a7a975db00217ad42366dacfb2f5a2b501d9a5cf138d2c1f340e6aa03257c13fc0d4e545263fa79e9f4735925a6828c637d0b901caf0e831b5ff95f610a

test:
  secret_key_base: 24736f87947469b2a8f6ae75525e2f4ff34d4bd359e2f53760329372de8542c4f8a0a6819555690dd2cd0c9420ff43005f17d9f75027f009a16c17483b960215

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
